version: 2.1

orbs:
  android: circleci/android@0.2.1
  run-with-retry: kimh/run-with-retry@1.0.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run-with-retry:
          command: ./gradlew assembleDebug