version: 2.1

orbs:
  android: circleci/android@sha256:b6646fdf7457f61825526e7bfce364d8e533da6ceb1cdb98e371e94348ecc834
  run-with-retry: kimh/run-with-retry@1.0.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run-with-retry/run-with-retry:
          command: ./gradlew assembleDebug