version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29-node
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3200m"
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy=in-process  

orbs:
  run-with-retry: kimh/run-with-retry@1.0.0    

jobs:
  build:
    executor: android-executor
            
    steps:
      - checkout
      - run-with-retry/run-with-retry:
          command: ./gradlew assembleDebug