version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android@sha256:b6646fdf7457f61825526e7bfce364d8e533da6ceb1cdb98e371e94348ecc834
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3200m"
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy=in-process  

orbs:
  run-with-retry: kimh/run-with-retry@1.0.0 

jobs:
  assemble_debug:
    executor: android-executor
            
    steps:
      - checkout
      - run:
          name: Assemble Debug
          command: ./gradlew assembleDebug

  assemble_release:
    executor: android-executor
            
    steps:
      - checkout
      - run:
          name: Assemble Release
          command: ./gradlew assembleRelease
  
workflows:
  version: 2.1
  build:
    jobs:
        - assemble_debug
        - assemble_release     
