steps:

  - command: ./gradlew testDebugUnitTest
    parallelism: 3
    branches: "master"
    artifact_paths: "build/**/*.xml"
  - wait: ~
    continue_on_failure: true
  - plugins:
      - junit-annotate#v1.8.0:
          artifacts: "build/**/*.xml"
  - label: "Build Debug"
    command: "./gradlew :app:assembleDebug"
    artifact_paths: "app/**/*.apk"
    branches: "master"
  - label: "Build Release"
    command: "./gradlew :app:assembleRelease"
    artifact_paths: "app/**/*.apk"
    branches: "master"
      