pipeline {      
    agent any
    parameters { 
        booleanParam(name: 'SHOULD_RELEASE', defaultValue: false, description: 'Should we release this build?')
    }

    stages {
        stage('Preparation') { 
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                echo "xplat_dbapp_android_lxc"
                echo "Release this build? ${params.SHOULD_RELEASE}"
            }
        }
    }
}